### Crear Alojamiento
POST http://localhost:8080/api/alojamientos
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="alojamiento"
Content-Type: application/json

{
  "titulo": "Hotel 777 2",
  "descripcion": "Un hotel parchado 2",
  "maxHuespedes": 4,
  "direccion": {
    "ciudad": "Armenia",
    "direccion": "cra 14",
    "localizacion": {
      "latitud": 30,
      "longitud": -100
    }
  },
  "precioPorNoche": 200.0,
  "servicios": [
    "PISCINA",
    "DESAYUNO"
  ]
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagenes"; filename="438485075.jpg"
Content-Type: image/jpeg

< C:\Users\FELIPE\Downloads\438485075.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagenes"; filename="729357497.jpg"
Content-Type: image/jpeg

< C:\Users\FELIPE\Downloads\729357497.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--
### Actualizar Alojamiento
PUT http://localhost:8080/api/alojamientos/1
Authorization: Bearer {{auth_token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="alojamiento"
Content-Type: application/json

{
  "titulo": "Hotel 777 EDITADO",
  "descripcion": "Un hotel parchado EDITADO",
  "maxHuespedes": 4,
  "direccion": {
    "ciudad": "Armenia",
    "direccion": "cra 14",
    "localizacion": {
      "latitud": 30,
      "longitud": -100
    }
  },
  "precioPorNoche": 200.0,
  "servicios": [
    "PISCINA",
    "DESAYUNO"
  ],
  "imagenes": [

  ]
}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagenes"; filename="438485076.jpg"
Content-Type: image/jpeg

< C:\Users\FELIPE\Downloads\438485076.jpg

### Obtener Alojamiento del Usuario
GET http://localhost:8080/api/alojamientos?pagina=0
Accept: application/json
Authorization: Bearer {{auth_token}}

### Obtener Alojamiento
GET http://localhost:8080/api/alojamientos/1
Accept: application/json