### Obtener usuario por id (200)
GET http://localhost:8080/api/usuarios/797d814a-5fd0-4953-810d-f593ff73928f
Accept: application/json

### Eliminar usuario (DELETE) (204)
DELETE http://localhost:8080/api/usuarios/1

### Cambiar contraseña (PATCH) (200) — usa CambioContrasenaDTO
PATCH http://localhost:8080/api/usuarios/1ccd6ad2-6ab3-4987-996c-99bdffd2905d/contrasena
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRhdmlkLnBvc3NvQGV4YW1wbGUuY29tIiwicm9sZSI6IlJPTF9IdWVzcGVkIiwibmFtZSI6IkRhdmlkIFBvc3NvIiwic3ViIjoiMWNjZDZhZDItNmFiMy00OTg3LTk5NmMtOTliZGZmZDI5MDVkIiwiaWF0IjoxNzU5NjIzMzMwLCJleHAiOjE3NTk2MjY5MzB9.3rtGWaRc2AgLU8hHAIb4Not5SOOcLyFrZc-Mtzvryb8

{
  "contrasenaActual": "Passw0rd1",
  "contrasenaNueva": "Pass0123"
}

### Editar usuario (PUT) (200)
PUT http://localhost:8080/api/usuarios/4c4e2933-899e-469a-b883-7ab9fe75a641
Content-Type: multipart/form-data; boundary=simpleboundary
Authorization: Bearer {{auth_token}}

--simpleboundary
Content-Disposition: form-data; name="usuario"
Content-Type: application/json

{
  "nombre": "David Felipe Pedraza",
  "telefono": "3102399644",
  "fechaNacimiento": "2025-08-30",
  "rol": "Huesped"
}

--simpleboundary
Content-Disposition: form-data; name="foto"; filename="Alucard pixel art.png"
Content-Type: image/png

< C:\Users\FELIPE\OneDrive\Imágenes\Saved Pictures\Alucard pixel art.png
--simpleboundary--

### Crear Anfitrion (POST)
POST http://localhost:8080/api/usuarios/anfitrion
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "usuarioId": "6fdc6cce-508b-433d-9069-638a4283252d",
  "sobreMi": "Me gusta el baloncesto",
  "documentoLegal": "documento.pdf"
}
